apiVersion: v1
kind: Secret
metadata:
  name: colabot-dev-1-secret
type: Opaque
data:
  tls.crt: ${{ secrets.TLS_CRT_DEV }}
  tls.key: ${{ secrets.TLS_KEY_DEV }}
stringData:
  access_token: ${{ secrets.ACCESS_TOKEN_DEV }}
  cml_password: ${{ secrets.CML_PASSWORD }}
  api_secret: ${{ secrets.API_SECRET }}
  mongo_initb_root_password: ${{ secrets.MONGO_DB_ROOT_PASSWORD }}
  awx_password: ${{ secrets.AWX_PASSWORD }}
  nlp_secret: ${{ secrets.NLP_SECRET }}
  aws_password: ${{ secrets.AWS_PASSWORD }}
