name: Colabot PY CI
on:
  pull_request:
    branches: [dev]
jobs:
  linting:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10.0]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - run: pip install virtualenv
    - run: make pylint
    - run: make check-format

  deploy:
    runs-on: ubuntu-latest

    env:
      REGISTRY: ghcr.io # registry
      IMAGE_NAME: ${{ github.repository }} # "ciscops/colabot-dev"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_PASS }} # set up secret token with access rights to packages

      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} # name of image

      #- run: kubectl apply -f colabot-manifest-dev.yaml # Deploy to kubernetes
      - run: kubectl config view #for debugging purposes
      #-run: kubectl rollout restart deployment/colabot-dev-1 # Verify deployment
