name: Colabot PY CI
on:
  pull_request:
    branches: [dev]
jobs:
  linting:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10.0]
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - run: pip install virtualenv
    - run: make pylint
    - run: make check-format

  deploy:
    runs-on: self-hosted

    env:
      REGISTRY: ghcr.io # registry
      IMAGE_NAME: ${{ github.repository }} # "ciscops/colabot-dev"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to GHCR
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_PASS }} # set up secret token with access rights to packages

      - name: Build and push image
        uses: docker/build-push-action@v2
        with:
          network: host
          context: ./
          file: ./Dockerfile
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} # name of image

      - name: Get kubeConfig file from secrets
        run: |
          mkdir ${HOME}/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > ${HOME}/.kube/config
      #cat ${HOME}/.kube/config  possibly for debugging, not needed
      #

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.EKS_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.EKS_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Apply and rollout
        run: |
          kubectl apply -f colabot-manifest-dev.yaml
          kubectl rollout restart deployment/colabot-dev-1
